# Based on https://raw.githubusercontent.com/dart-lang/intl/master/.github/workflows/test-package.yml
name: Test and Analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  # Check code formatting and static analysis on a single OS (linux)
  # against Dart dev.
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [dev, stable]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter and Pub Dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ matrix.os }}-flutter-cache-${{ matrix.channel }}-${{ hashFiles('pubspec.yaml') }}
      - name: Install Flutter
        uses: subosito/flutter-action@14cf1a3f117efa3893f2de5442aad22d32295efc
        with:
          channel: ${{ matrix.channel }}
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
      - name: Analyze code
        run: dart analyze --fatal-infos
        if: always() && steps.install.outcome == 'success'

  # Run tests on a matrix consisting of two dimensions:
  # 1. OS: ubuntu-latest, (macos-latest, windows-latest)
  # 2. release channel: dev
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Add macos-latest and/or windows-latest if relevant for this package.
        os: [ubuntu-latest]
        channel: [dev, stable]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter and Pub Dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ matrix.os }}-flutter-cache-${{ matrix.channel }}-${{ hashFiles('pubspec.yaml') }}
      - name: Install Flutter
        uses: subosito/flutter-action@14cf1a3f117efa3893f2de5442aad22d32295efc
        with:
          channel: ${{ matrix.channel }}
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Run VM tests
        run: flutter test
        if: always() && steps.install.outcome == 'success'
